import type { TileSpec } from './types';

/** Starter tile library. Every design carries its own editable copy of the tiles it uses. */
export const TILE_PRESETS: TileSpec[] = [
  {
    // Floor & Decor #101488179 — Capri Oat, 12×24 matte porcelain, limestone look, ~8 mm
    id: 'capri-oat-12x24',
    name: 'Capri Oat 12×24',
    width: 24,
    height: 12,
    thickness: 0.315,
    pattern: 'third',
    colors: ['#d8cdbb', '#d2c6b2', '#dcd2c2', '#cfc2ad'],
    variation: 0.35,
    finish: 'matte',
    surface: 'concrete',
    edge: 'eased',
    groutWidth: 0.125,
    groutColor: '#cbc1b1',
  },
  {
    // Floor & Decor #101068773 — La Belle Sage, 3×12 high-gloss ceramic, 8.5 mm, soft wavy glaze
    id: 'la-belle-sage-3x12',
    name: 'La Belle Sage 3×12',
    width: 12,
    height: 3,
    thickness: 0.335,
    pattern: 'running',
    colors: ['#9fae95', '#a6b49b', '#97a88d', '#aab79f'],
    variation: 0.45,
    finish: 'gloss',
    surface: 'handmade',
    edge: 'pillowed',
    groutWidth: 0.0625,
    groutColor: '#e1dfd6',
  },
  {
    id: 'limestone-12x24',
    name: 'Honed limestone',
    width: 24,
    height: 12,
    thickness: 0.375,
    pattern: 'third',
    colors: ['#d9d0c1', '#d3c9b8', '#ddd5c8'],
    variation: 0.35,
    finish: 'matte',
    surface: 'concrete',
    edge: 'eased',
    groutWidth: 0.0625,
    groutColor: '#c8bfb1',
  },
  {
    id: 'zellige-ivory-4x4',
    name: 'Zellige ivory',
    width: 4,
    height: 4,
    thickness: 0.5,
    pattern: 'grid',
    colors: ['#f1ede4', '#ece6d9', '#f4f1ea', '#e8e1d2'],
    variation: 0.4,
    finish: 'gloss',
    surface: 'zellige',
    edge: 'pillowed',
    groutWidth: 0.0625,
    groutColor: '#ddd5c6',
  },
  {
    id: 'subway-handmade-sage',
    name: 'Handmade sage 2½×8',
    width: 2.5,
    height: 8,
    thickness: 0.375,
    pattern: 'vertical',
    colors: ['#a9b39b', '#9fab92', '#b3bca5'],
    variation: 0.45,
    finish: 'gloss',
    surface: 'handmade',
    edge: 'pillowed',
    groutWidth: 0.0625,
    groutColor: '#d7d3c8',
  },
  {
    id: 'subway-white-3x12',
    name: 'Glossy white 3×12',
    width: 12,
    height: 3,
    thickness: 0.375,
    pattern: 'running',
    colors: ['#f5f4f0', '#f1efea'],
    variation: 0.15,
    finish: 'gloss',
    surface: 'handmade',
    edge: 'eased',
    groutWidth: 0.0625,
    groutColor: '#e4e2dc',
  },
  {
    id: 'calacatta-24x48',
    name: 'Calacatta porcelain slab',
    width: 24,
    height: 48,
    thickness: 0.375,
    pattern: 'grid',
    colors: ['#f2efea'],
    variation: 0.1,
    finish: 'satin',
    surface: 'marble',
    edge: 'square',
    groutWidth: 0.0625,
    groutColor: '#e7e3dc',
    vein: '#8f8a84',
  },
  {
    id: 'hex-carrara-3',
    name: 'Carrara hex 3″',
    width: 3,
    height: 3,
    thickness: 0.375,
    pattern: 'hex',
    colors: ['#e9e8e5', '#e2e1de', '#efeeeb'],
    variation: 0.4,
    finish: 'satin',
    surface: 'marble',
    edge: 'eased',
    groutWidth: 0.0625,
    groutColor: '#cfcdc8',
    vein: '#9c9a97',
  },
  {
    id: 'terracotta-8x8',
    name: 'Terracotta 8×8',
    width: 8,
    height: 8,
    thickness: 0.5,
    pattern: 'grid',
    colors: ['#b8704f', '#a8633f', '#c07b58', '#b0694a'],
    variation: 0.55,
    finish: 'matte',
    surface: 'handmade',
    edge: 'eased',
    groutWidth: 0.25,
    groutColor: '#cdbfae',
  },
  {
    id: 'terrazzo-24x24',
    name: 'Terrazzo 24×24',
    width: 24,
    height: 24,
    thickness: 0.5,
    pattern: 'grid',
    colors: ['#e6e0d6'],
    variation: 0.05,
    finish: 'satin',
    surface: 'terrazzo',
    edge: 'square',
    groutWidth: 0.0625,
    groutColor: '#d9d2c6',
  },
  {
    id: 'herringbone-2x8-clay',
    name: 'Clay herringbone 2×8',
    width: 8,
    height: 2,
    thickness: 0.375,
    pattern: 'herringbone',
    colors: ['#d4bfa6', '#cbb398', '#dac8b2'],
    variation: 0.5,
    finish: 'matte',
    surface: 'handmade',
    edge: 'eased',
    groutWidth: 0.0625,
    groutColor: '#e3d9cb',
  },
  {
    id: 'forest-4x4-gloss',
    name: 'Deep green 4×4',
    width: 4,
    height: 4,
    thickness: 0.375,
    pattern: 'grid',
    colors: ['#2f4a3e', '#35503f', '#2a4438', '#3a5646'],
    variation: 0.6,
    finish: 'gloss',
    surface: 'zellige',
    edge: 'pillowed',
    groutWidth: 0.0625,
    groutColor: '#cfcabe',
  },
  {
    id: 'basketweave-marble',
    name: 'Marble basketweave',
    width: 6,
    height: 3,
    thickness: 0.375,
    pattern: 'basketweave',
    colors: ['#ebe9e5', '#e4e2de'],
    variation: 0.3,
    finish: 'satin',
    surface: 'marble',
    edge: 'eased',
    groutWidth: 0.0625,
    groutColor: '#d7d4ce',
    vein: '#a7a39d',
  },
];

export const PAINT_SWATCHES: { name: string; hex: string }[] = [
  { name: 'Linen white', hex: '#ece6dc' },
  { name: 'Bone', hex: '#e2dacb' },
  { name: 'Pure white', hex: '#f3f2ee' },
  { name: 'Mushroom', hex: '#cbbfae' },
  { name: 'Plaster pink', hex: '#e2c8b8' },
  { name: 'Sage', hex: '#b5bba5' },
  { name: 'Eucalyptus', hex: '#8e9a86' },
  { name: 'Mist blue', hex: '#bcc7c8' },
  { name: 'Ochre', hex: '#c9a66b' },
  { name: 'Terracotta', hex: '#b67658' },
  { name: 'Olive', hex: '#6d6a4b' },
  { name: 'Ink', hex: '#2d3438' },
];
