import {
  Archive,
  AppWindow,
  Bath,
  BookOpen,
  Box,
  DoorOpen,
  Flower2,
  Frame,
  Image,
  GlassWater,
  Lamp,
  Plug,
  ToggleRight,
  LampCeiling,
  LampWallUp,
  PanelTop,
  RectangleVertical,
  ShowerHead,
  Sprout,
  Toilet,
  Waves,
  type LucideIcon,
} from 'lucide-react';

export const ITEM_ICONS: Record<string, LucideIcon> = {
  vanity: PanelTop,
  linen: Archive,
  tub: Bath,
  toilet: Toilet,
  'shower-trim': ShowerHead,
  'glass-panel': RectangleVertical,
  curtain: Waves,
  mirror: Frame,
  sconce: LampWallUp,
  'ceiling-light': LampCeiling,
  'towel-bar': BookOpen,
  'robe-hook': Lamp,
  'tp-holder': Box,
  'towel-ring': BookOpen,
  art: Image,
  switch: ToggleRight,
  outlet: Plug,
  shelf: PanelTop,
  rug: AppWindow,
  plant: Sprout,
  'vanity-decor': Flower2,
  door: DoorOpen,
  glass: GlassWater,
};
